// @ts-check
import { test, expect } from './baseTest';
import { loadAndSignIn, mockRequests } from './utilities';

test('submits a report', async ({ page }) => {
  await mockRequests(page);
  await loadAndSignIn(page);

  await page.getByRole('button', { name: 'Marker' }).first().click();
  await page.getByRole('button', { name: '' }).first().click();
  await page.locator('.map').first().click();
  await page.getByRole('button', { name: '' }).nth(1).click();
  await page.locator('.map').first().click();
  await page.getByRole('button', { name: 'Verify Location' }).click();
  await page.getByLabel('Collection Date').fill('2024-04-17');
  await page.locator('[id="downshift-\\:r7\\:-toggle-button"]').click();
  await page.getByRole('option', { name: 'Depletion estimate' }).click();
  await page.getByLabel('Observers').click();
  await page.getByLabel('Observers').fill('test observer');
  await page.getByRole('link', { name: 'Method' }).click();
  await page.locator('#MODEL_input').click();
  await page.locator('#MODEL_input').fill('s');
  await page.locator('#MODEL_input').press('Enter');
  await page.locator('#MODEL_input').press('Tab');
  await page.locator('#NUM_NETTERS_input').fill('1');
  await page.locator('#NUM_NETTERS_input').press('Tab');
  await page.locator('#NUM_ANODES_input').fill('2');
  await page.locator('#NUM_ANODES_input').press('Tab');
  await page.locator('#numeric-input-cell-0-ANODE_DIAMETER').fill('2');
  await page.locator('#numeric-input-cell-0-ANODE_DIAMETER').press('Tab');
  await page.locator('#numeric-input-cell-0-STOCK_DIAMETER').fill('2');
  await page.locator('#numeric-input-cell-0-STOCK_DIAMETER').press('Tab');

  await page.getByRole('link', { name: 'Catch' }).click();
  await page.locator('#dropdown-0-SPECIES_CODE').click();
  await page.locator('#dropdown-0-SPECIES_CODE').fill('s');
  await page.getByRole('option', { name: 'SCPU' }).click();
  await page.locator('#dropdown-0-SPECIES_CODE').press('Tab');
  await page.locator('#dropdown-0-LENGTH_TYPE').fill('s');
  await page.locator('#dropdown-0-LENGTH_TYPE').press('Tab');
  await page.locator('#numeric-input-cell-0-LENGTH').fill('2');
  await page.locator('#numeric-input-cell-0-LENGTH').press('Tab');
  await page.locator('#numeric-input-cell-0-WEIGHT').fill('2');
  await page.locator('#numeric-input-cell-0-WEIGHT').press('Tab');
  await page.locator('#numeric-input-cell-0-COUNT').press('Tab');
  await page.getByRole('button', { name: 'Diet' }).click();
  await page.locator('#dropdown-0-CLASS').click();
  await page.locator('#dropdown-0-CLASS').fill('');
  await page.locator('#dropdown-0-CLASS').press('Tab');
  await page.locator('a').filter({ hasText: 'Health' }).click();
  await page.locator('[id="downshift-\\:r1n\\:-toggle-button"]').click();
  await page.locator('#Health_tab').getByText('Blind (1)').click();
  await page.getByText('OK', { exact: true }).click();
  await page.getByRole('link', { name: 'Habitat' }).click();
  await page.locator('#BANKVEG_input').click();
  await page.locator('#BANKVEG_input').fill('24');
  await page.locator('#SUB_FINES_input').click();
  await page.locator('#SUB_FINES_input').fill('30');
  await page.locator('#SUB_FINES_input').press('Tab');
  await page.locator('#SUB_SAND_input').fill('30');
  await page.locator('#SUB_SAND_input').press('Tab');
  await page.locator('#SUB_GRAV_input').fill('30');
  await page.locator('#SUB_GRAV_input').press('Tab');
  await page.locator('#SUB_COBB_input').fill('1');
  await page.locator('#SUB_COBB_input').press('Tab');
  await page.locator('#SUB_RUBB_input').fill('1');
  await page.locator('#SUB_RUBB_input').press('Tab');
  await page.locator('#SUB_BOUL_input').fill('1');
  await page.locator('#SUB_BOUL_input').press('Tab');
  await page.locator('#SUB_BEDR_input').fill('7');
  await page.locator('#SUB_BEDR_input').press('Tab');
  await page.getByRole('button', { name: 'Submit Report' }).click();
  await page.getByTestId('summaryConfirmBtn').click();
  await expect(page.locator('#root')).toContainText('The report has been submitted successfully');
});
